# Generated by Django 2.2 on 2022-06-26 18:06

import apps.message.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('from_type', models.CharField(choices=[('issues', '动态消息'), ('user', '用户私信'), ('shop', '商城消息')], max_length=10, verbose_name='消息源')),
                ('message_content', models.TextField(verbose_name='消息内容')),
                ('from_user', djongo.models.fields.EmbeddedField(blank=True, default={'user_id': -1, 'username': 'system'}, model_container=apps.message.models.UserEntity, null=True)),
                ('to_user', djongo.models.fields.EmbeddedField(model_container=apps.message.models.UserEntity)),
                ('created_time', models.DateTimeField()),
                ('has_consumed', models.BooleanField(default=False, verbose_name='是否已被消费')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
            },
        ),
    ]
