# Generated by Django 2.2 on 2022-07-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20220709_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='source_type',
            field=models.CharField(choices=[('issues', '动态消息'), ('user', '用户私信'), ('shop', '商城消息'), ('system', '系统消息'), ('comment', '评论消息'), ('thumbs_up', '点赞消息')], max_length=10, verbose_name='消息源'),
        ),
    ]
